/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common.ts';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base.ts';
// @ts-ignore
import type { CategoryCount } from '../models';
// @ts-ignore
import type { Product } from '../models';
/**
 * FleamarketControllerApi - axios parameter creator
 * @export
 */
export const FleamarketControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gibt eine Liste von Kategorien-Objekten(Name und Produktanzahl) zurück.
         * @summary Alle Kategorien abrufen
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gibt eine Liste von Produkten zurück
         * @summary Produkte abrufen
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchProducts: async (search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FleamarketControllerApi - functional programming interface
 * @export
 */
export const FleamarketControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FleamarketControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Gibt eine Liste von Kategorien-Objekten(Name und Produktanzahl) zurück.
         * @summary Alle Kategorien abrufen
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchCategories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CategoryCount>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchCategories(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleamarketControllerApi.searchCategories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gibt eine Liste von Produkten zurück
         * @summary Produkte abrufen
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchProducts(search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Product>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchProducts(search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleamarketControllerApi.searchProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FleamarketControllerApi - factory interface
 * @export
 */
export const FleamarketControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FleamarketControllerApiFp(configuration)
    return {
        /**
         * Gibt eine Liste von Kategorien-Objekten(Name und Produktanzahl) zurück.
         * @summary Alle Kategorien abrufen
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchCategories(options?: RawAxiosRequestConfig): AxiosPromise<Array<CategoryCount>> {
            return localVarFp.searchCategories(options).then((request) => request(axios, basePath));
        },
        /**
         * Gibt eine Liste von Produkten zurück
         * @summary Produkte abrufen
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchProducts(search?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Product>> {
            return localVarFp.searchProducts(search, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FleamarketControllerApi - object-oriented interface
 * @export
 * @class FleamarketControllerApi
 * @extends {BaseAPI}
 */
export class FleamarketControllerApi extends BaseAPI {
    /**
     * Gibt eine Liste von Kategorien-Objekten(Name und Produktanzahl) zurück.
     * @summary Alle Kategorien abrufen
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FleamarketControllerApi
     */
    public searchCategories(options?: RawAxiosRequestConfig) {
        return FleamarketControllerApiFp(this.configuration).searchCategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gibt eine Liste von Produkten zurück
     * @summary Produkte abrufen
     * @param {string} [search] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FleamarketControllerApi
     */
    public searchProducts(search?: string, options?: RawAxiosRequestConfig) {
        return FleamarketControllerApiFp(this.configuration).searchProducts(search, options).then((request) => request(this.axios, this.basePath));
    }
}

